server:
  port: 10000

spring:
  datasource:
    url: jdbc:mysql://192.168.176.129:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  # 项目名
  application:
    name: gulimall-product
  # 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # json时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # 关闭thymeleaf缓存
  thymeleaf:
    cache: false

  # redis
  redis:
    host: 192.168.176.129
    port: 6379

  # cache:使用redis作为缓存
  cache:
    type: redis
    # 生存时间
    redis:
      time-to-live: 3600000
    # 前缀，不指定，默认分区名作为前缀
      #key-prefix:
    # 前缀生效
      use-key-prefix: true
    # 是否存null值，防止缓存击穿
      cache-null-values: true

mybatis-plus:
  #classpath*：多一个星代表不止工程的包扫描，其他引用的包也扫描
  mapper-locations: classpath:/mapper/**/*.xml
  #主键自增
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除
      logic-delete-field: show_status  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2(@TableLogic注解))
      # 这的逻辑与数据库相反，可以在这里改，也可以在注解上修改
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

# 日志级别，打印逻辑删除sql语句
logging:
  level:
    com.wkl.gulimall.product: error